name: CI

# Controls when the workflow will run
on: 
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ci:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./source

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Linting
        run: npm run lint
      - name: Formatting
        run: npm run format
      - name: Doc Gen
        run: npm run docs
      - name: Upload JSDoc
        uses: actions/upload-artifact@v4
        with:
          name: jsdoc
          path: ./source/docs
